spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/coachforyou
    username: coach4you
    password: coach4you
    driver-class-name: org.postgresql.Driver
  flyway:
    locations: classpath:db/migration/prod
    baseline-on-migrate: true
    enabled: true
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
server:
  servlet:
    context-path: /coach4you

logging:
  level:
    org:
      flywaydb: debug